server:
  port: 801


#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
#      username: root
#      password: 123456
#
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tb_
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl